"""
Duplication Detection Probes (Clean version)
=============================================
Cole's ask: Binary classifier predicting whether a prompt contains a repeated name.
- IOI prompts (label=1): contain a repeated name (S appears twice)
- Control prompts (label=0): same prompts but S2 token replaced with a third name

Probed at END and S2 positions, all layers, steps 1000-143000.
Uses sklearn LogisticRegression.

Fix: control prompts generated by token-level replacement of S2, not string hacking.
"""

import os
os.environ["HF_TOKEN"] = ""

import torch, json, time, numpy as np, sys, random
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import accuracy_score

sys.path.insert(0, '/workspace/MLP-Paper-Cole/src')
from transformers import AutoModelForCausalLM
from transformer_lens import HookedTransformer
from circuitscaling.datasets import IOIDataset, ALL_TEMPLATES, CANDIDATE_NAMES

DEVICE = "cuda"
MODEL_NAME = "EleutherAI/pythia-160m-deduped"
TEMPLATES = ALL_TEMPLATES[:15]
PPT = 30
SEED = 42
RESULTS_FILE = "results/duplication_probes.json"

def empty_cache():
    torch.cuda.empty_cache()

def save_results(results):
    with open(RESULTS_FILE, "w") as f:
        json.dump(results, f, indent=2, default=str)

def get_s2_positions(tokens, s_ids):
    """Find S2 position for each example."""
    s2_positions = []
    for i in range(tokens.shape[0]):
        s_tok = s_ids[i].item()
        s_count = 0
        s2_pos = -1
        for j in range(1, tokens.shape[1]):
            if tokens[i, j].item() == s_tok:
                s_count += 1
                if s_count == 2:
                    s2_pos = j
                    break
        s2_positions.append(s2_pos)
    return s2_positions

def load_model(step):
    hf = AutoModelForCausalLM.from_pretrained(MODEL_NAME, revision="step%d" % step)
    model = HookedTransformer.from_pretrained(
        MODEL_NAME, hf_model=hf, device=DEVICE,
        center_writing_weights=True, center_unembed=True, fold_ln=True)
    del hf
    return model

def run_probes(results):
    probe_steps = [1000, 2000, 3000, 5000, 10000, 143000]
    n_layers = 12
    random.seed(SEED)

    # Build a set of single-token names for replacement
    # We need names that tokenize to a single token
    tokenizer = HookedTransformer.from_pretrained(MODEL_NAME, device="cpu").tokenizer
    single_token_names = []
    for name in CANDIDATE_NAMES:
        toks = tokenizer.encode(" " + name, add_special_tokens=False)
        if len(toks) == 1:
            single_token_names.append((name, toks[0]))
    print("Single-token names available: %d" % len(single_token_names))
    del tokenizer

    for step in probe_steps:
        step_key = "step_%d" % step
        if step_key in results:
            print("Step %d done, skip" % step)
            continue

        print("\n=== Step %d ===" % step)
        model = load_model(step)

        # Collect activations
        all_end_activations = {l: [] for l in range(n_layers)}
        all_s2_activations = {l: [] for l in range(n_layers)}
        all_labels = []

        for tmpl in TEMPLATES:
            try:
                ds = IOIDataset(model=model, n_prompts=PPT, templates=[tmpl],
                                symmetric=True, seed=SEED)
                tokens = model.to_tokens(ds.prompts).to(DEVICE)
                io_ids = torch.tensor(ds.io_token_ids, device=DEVICE)
                s_ids = torch.tensor(ds.s_token_ids, device=DEVICE)

                final_pos = tokens.shape[1] - 1
                s2_positions = get_s2_positions(tokens, s_ids)

                # === IOI prompts (label = 1, has repeated name) ===
                _, cache_ioi = model.run_with_cache(tokens, remove_batch_dim=False)

                for layer in range(n_layers):
                    resid = cache_ioi["blocks.%d.hook_resid_post" % layer]
                    for i in range(tokens.shape[0]):
                        all_end_activations[layer].append(
                            resid[i, final_pos, :].detach().cpu().float().numpy())
                        if s2_positions[i] > 0:
                            all_s2_activations[layer].append(
                                resid[i, s2_positions[i], :].detach().cpu().float().numpy())

                for i in range(tokens.shape[0]):
                    all_labels.append(1)

                del cache_ioi; empty_cache()

                # === Control prompts (label = 0, no repeated name) ===
                # Replace S2 token with a different single-token name
                control_tokens = tokens.clone()
                valid_control = []

                for i in range(tokens.shape[0]):
                    s2_pos = s2_positions[i]
                    if s2_pos <= 0:
                        valid_control.append(False)
                        continue

                    s_tok = s_ids[i].item()
                    io_tok = io_ids[i].item()

                    # Pick a third name that's different from both IO and S
                    candidates = [(name, tok_id) for name, tok_id in single_token_names
                                  if tok_id != s_tok and tok_id != io_tok]
                    if not candidates:
                        valid_control.append(False)
                        continue

                    third_name, third_tok = random.choice(candidates)
                    control_tokens[i, s2_pos] = third_tok
                    valid_control.append(True)

                # Run control through model
                _, cache_ctrl = model.run_with_cache(control_tokens, remove_batch_dim=False)

                for layer in range(n_layers):
                    resid = cache_ctrl["blocks.%d.hook_resid_post" % layer]
                    for i in range(tokens.shape[0]):
                        if valid_control[i]:
                            all_end_activations[layer].append(
                                resid[i, final_pos, :].detach().cpu().float().numpy())
                            if s2_positions[i] > 0:
                                all_s2_activations[layer].append(
                                    resid[i, s2_positions[i], :].detach().cpu().float().numpy())

                for i in range(tokens.shape[0]):
                    if valid_control[i]:
                        all_labels.append(0)

                del cache_ctrl; empty_cache()

            except Exception as e:
                print("  Template failed: %s" % str(e)[:60])
                continue

        labels = np.array(all_labels)
        n_pos = int(labels.sum())
        n_neg = int((1 - labels).sum())
        print("  Collected: %d IOI (label=1), %d control (label=0)" % (n_pos, n_neg))

        if n_pos < 20 or n_neg < 20:
            print("  Too few examples, skip")
            del model; empty_cache()
            continue

        # Verify balance
        print("  Label balance: %.1f%% positive" % (n_pos / len(labels) * 100))

        # Verify control prompts are different
        print("  Sanity check: first few labels = %s" % labels[:10].tolist())

        step_results = {"n_ioi": n_pos, "n_control": n_neg}

        for pos_name, activations in [("END", all_end_activations), ("S2", all_s2_activations)]:
            pos_results = {}
            for layer in range(n_layers):
                X = np.array(activations[layer])
                n_samples = min(len(X), len(labels))
                if n_samples < 40:
                    continue
                X = X[:n_samples]
                y = labels[:n_samples]

                # 5-fold cross-validation for robust estimate
                skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=SEED)
                fold_accs_train = []
                fold_accs_test = []

                for train_idx, test_idx in skf.split(X, y):
                    X_train, X_test = X[train_idx], X[test_idx]
                    y_train, y_test = y[train_idx], y[test_idx]

                    clf = LogisticRegression(max_iter=2000, random_state=SEED, C=1.0)
                    clf.fit(X_train, y_train)

                    fold_accs_train.append(accuracy_score(y_train, clf.predict(X_train)))
                    fold_accs_test.append(accuracy_score(y_test, clf.predict(X_test)))

                mean_train = float(np.mean(fold_accs_train))
                mean_test = float(np.mean(fold_accs_test))
                std_test = float(np.std(fold_accs_test))

                pos_results["layer_%d" % layer] = {
                    "train_acc": round(mean_train, 4),
                    "test_acc": round(mean_test, 4),
                    "test_std": round(std_test, 4),
                }

            step_results[pos_name] = pos_results

            # Print summary
            print("  %s position:" % pos_name)
            for l in sorted(pos_results.keys(), key=lambda x: int(x.split('_')[1])):
                r = pos_results[l]
                bar = "#" * int(r["test_acc"] * 20)
                marker = " ***" if r["test_acc"] > 0.65 else ""
                print("    %s: train=%.1f%% test=%.1f%% (±%.1f%%) %s%s" % (
                    l, r["train_acc"] * 100, r["test_acc"] * 100,
                    r["test_std"] * 100, bar, marker))

        results[step_key] = step_results
        save_results(results)

        del model; empty_cache()


def main():
    print("=" * 60)
    print("  DUPLICATION DETECTION PROBES")
    print("  Binary: repeated name (IOI) vs no repetition (control)")
    print("  Positions: END and S2")
    print("  Method: sklearn LogisticRegression, 5-fold CV")
    print("  Started: %s" % time.strftime("%Y-%m-%d %H:%M:%S"))
    print("=" * 60)

    if os.path.exists(RESULTS_FILE):
        with open(RESULTS_FILE) as f:
            results = json.load(f)
    else:
        results = {}

    t0 = time.time()
    run_probes(results)
    elapsed = time.time() - t0

    # Final summary
    print("\n" + "=" * 60)
    print("  SUMMARY")
    print("=" * 60)
    for step in sorted(results.keys(), key=lambda x: int(x.split('_')[1])):
        r = results[step]
        print("  %s:" % step)
        for pos in ["END", "S2"]:
            if pos in r:
                best_layer = max(r[pos].keys(), key=lambda l: r[pos][l]["test_acc"])
                best_acc = r[pos][best_layer]["test_acc"]
                print("    %s: best=%s (%.1f%%)" % (pos, best_layer, best_acc * 100))

    print("\n  Time: %.1f minutes" % (elapsed / 60))
    print("  Results: %s" % RESULTS_FILE)
    print("=" * 60)


if __name__ == "__main__":
    main()
